export const LOAD_GALLERY_DATA = 'LOAD_GALLERY_DATA';
export const UPDATE_GALLERY_DATA = 'UPDATE_GALLERY_DATA';
export const UPDATE_SORT_DATA = 'UPDATE_SORT_DATA';
export const REMOVE_GALLERY_DATA = 'REMOVE_GALLERY_DATA';